"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const bodyParser = require("body-parser");
const users = require("./users");
const classes = require("./classes");
const roster = require("./roster");
const assignments = require("./assignments");
exports.router = express_1.Router();
exports.router.use(bodyParser.json());
exports.router.get("/", users.Redirect);
exports.router.use("/", users.Authenticate);
exports.router.param("userid", users.lookupUser);
exports.router.get("/users/", users.getAllUsers);
exports.router.post("/users/", users.createUser);
exports.router.get("/users/:userid", users.getOneUser);
exports.router.put("/users/:userid", users.updateUser);
exports.router.delete("/users/:userid", users.deleteUser);
exports.router.param("classid", classes.lookupClass);
exports.router.get("/classes/", classes.getAllClasses);
exports.router.get("/classes/:classid", classes.getOneClass);
exports.router.post("/classes/", classes.addClass);
exports.router.put("/classes/:classid", classes.updateClass);
exports.router.delete("/classes/:classid", classes.deleteClass);
exports.router.get("/rosters/:classid", roster.getAllStudentsInClass);
exports.router.put("/rosters/:classid/:userid", roster.addStudentToClass);
exports.router.delete("/rosters/:classid/:userid", roster.deleteStudentFromClass);
//router.param("assignnum", assignments.lookupAssignmentNumber);
exports.router.get("assignments/:classid", assignments.getAllAssignmentsInClass);
exports.router.get("assignments/:classid/:assignnum", assignments.getOneAssignmentInClass);
exports.router.post("assignments/:classid", assignments.addAssignmentToClass);
exports.router.put("assignments/:classid/:assignnum", assignments.updateAssignmentInClass);
exports.router.delete("assignments/:classid/:assignnum", assignments.deleteAssignmentFromClass);
//# sourceMappingURL=routes.js.map